from tkinter import*
from tkinter import messagebox
from tkinter import ttk
root=Tk()
root.title("Classes2")
root.geometry("600x600")
cd=ttk.Combobox(root,state="readonly",values="label button dropdown radiobutton",width=10)
cd.pack()
var=""
var2=""
class CreateElement:
    def _init_(self):
        print("this is a CreateElement class")
    def label(self):
        global var
        l=Label(root,text="a new label has been created by class",fg="plum")
        l.pack()
        r=Radiobutton(root,text="radio button",variable=var,value="")
        r.pack()
    def button(self):
        b=Button(root,text="a new button has been created by class",fg="black",bg="cornflowerblue")
        b.pack(padx=20,pady=10)
    def dropdown(self):
        d=ttk.Combobox(root,state="readonly",values="",width=10)
        d.pack()
    def radio(self):
        r=Radiobutton(root,text="radio button",variable=var,value="")
        r.pack()
        r2=Radiobutton(root,text="radio button",variable=var2,value="")
        r2.pack()
    def choose(self):
        element=cd.get()
        if(element=="label"):
            self.label()
        if(element=="button"):
            self.button()
        if(element=="dropdown"):
            self.dropdown()
        else:
            self.radio()                   
    def message(self):
        messagebox.showinfo("Showinfo","You clicked the button generated by class")
    
obj_of_CreateElement=CreateElement()
b1=Button(root,text="click to create a button and a label",command= obj_of_CreateElement.choose)
b1.pack(padx=20,pady=10)
root.mainloop()